### ISSUE TITLE
checkpw blocks infinitely when using flutter in release apk

### ISSUE THREAD

**Issue by devxpy** [Erly/dbcrypt#3] opened 2018-07-13 10:52 UTC
Please refer to [this](https://gist.github.com/devxpy/f3727a5937d4e1462766811c177bbaac) gist for code and logs.

**Comment by Erly** [comment] 2018-07-31 20:46
Oops I didn't see this issue was created until now, sorry. I'll check it tomorrow, but bear in mind flutter uses a dev version of the Dart 2 SDK and the released version of dBCrypt doesn't support yet Dart 2 (a version that supports it, is almost ready)

**Comment by Erly** [comment] 2018-08-01 19:58
I can't reproduce this issue with an Xperia X Performance (Android 8.0) on Windows, with the same Flutter and Android toolchain version and dBCrypt 0.2.0 😕 Could you try with a different phone or the code from the master branch that is Dart 2 ready? I'm not sure I can get a Nexus 5 to try it but I'll try it with the Xperia on Linux tomorrow just in case, but shouldn't make any difference.

**Comment by jeroentrappers** [comment] 2018-09-03 10:49
I am experiencing the same issue on a OnePlus 5T.

**Comment by devxpy** [comment] 2018-09-03 12:01
Making the API async won't do much since it's a CPU bound task.

But, using a dart `Isolate` to create a new thread and then get the results back using the inbuilt messaging functionality would solve the issue

**Comment by metacomgd** [comment] 2018-10-24 19:07
I am experiencing the same; On the debug apk it takes around 3 seconds to complete a hash a string, whereas the release apk (no code changes) it takes 160 seconds! Any eta on the dart2 version?

**Comment by NBTX** [comment] 2018-12-09 02:59
Can confirm this is still an issue.

**Comment by NBTX** [comment] 2018-12-17 15:19
This issue is caused by: https://github.com/flutter/flutter/issues/24906

**Comment by louia** [comment] 2019-06-14 13:42
It's not fix yet. WE ARE IN JULY 2019

**Comment by jeroentrappers** [comment] 2019-06-14 13:52
If you have a good fix, please send me a pull request.

**Comment by mbaghert** [comment] 2019-07-02 18:20
error not fixed

**Comment by NBTX** [comment] 2019-07-05 08:00
Has anyone still being affected by this error opened an issue in the Flutter repo?
If so, can you post it here?

**Comment by jeroentrappers** [comment] 2019-07-18 07:43
The issue is not that checkpw blocks infinitely, just that for a large cost factor it can take an incredible amount of time.

**Comment by Erly** [comment] 2019-08-12 15:01
With the last flutter stable version for me it takes 4 seconds to run the gist in the original post on my device, which may be too much but nowhere near blocking infinitely like it was originally reported. I think that problem was fixed in #https://github.com/flutter/flutter/issues/24906 and the problem right now it's related to #https://github.com/dart-lang/sdk/issues/37551 but can't try it yet since not even the dev channel has a SDK version with that fix yet.

**Closed** 2020-12-16 11:02 UTC
Labels: can't reproduce

**Comment by flawnn** [comment] 2021-05-19 22:12
I have this issue too on recent versions. Sadly, can't do nothing bout it. If anyone needs information, I will kindly provide

**Comment by jeroentrappers** [comment] 2021-05-19 22:15
@flawnn i made a native implementation for this exact reason: https://pub.dev/packages/flutter_bcrypt

**Comment by flawnn** [comment] 2021-05-19 22:16
> @flawnn i made a native implementation for this exact reason: https://pub.dev/packages/flutter_bcrypt

It seems like this wasn't updated for a long time. Null safety seems also not supported, that's a bit of a bummer.

**Comment by jeroentrappers** [comment] 2021-05-19 22:18
It works for me :-) PR welcome if you like to update it, or put null safety support in it.

**Comment by flawnn** [comment] 2021-05-19 22:54
> It works for me :-) PR welcome if you like to update it, or put null safety support in it.

https://github.com/jeroentrappers/flutter_bcrypt/pull/6
here you go ;)
works for me, migration was flawless

**Comment by flawnn** [comment] 2021-05-21 16:19
> It works for me :-) PR welcome if you like to update it, or put null safety support in it.

Kind reminder again to merge the PR, so other people can use the wonderful package too on higher SDK version :)

**Comment by jeroentrappers** [comment] 2021-05-21 18:45
> Kind reminder again to merge the PR, so other people can use the wonderful package too on higher SDK version :)

Done
